shivasurya/code-pathfinder

- .github/workflows/release.yml
added `-ldflags="-s -w"` flag for optimising binaries built in CI
> optimize binary - strip symbols

- sourcecode-parser/construct.go
- sourcecode-parser/model/javadoc_test.go
- sourcecode-parser/source_sink.go
Added annotation attr and now we could query
```sql
FIND method_declaration WHERE annotation = "@Deprecated" AND has_access = "true"
```
- Fixed overwriting issue with relating both method declaration and method invocation 
- added testcase for model/ package
- Fixed methodID generation bug, its overwriting similar name method names, variable names
> Added Annotation attr

- README.md
- discord invite link
- license
> Add discord and license badges

- sourcecode-parser/construct.go
- sourcecode-parser/model/javadoc.go
- sourcecode-parser/model/javadoc_test.go
- sourcecode-parser/source_sink.go
- Added new API to compute comment length
- Improve javadoc model
> Improve javadoc tag data structure

- .github/workflows/release.yml
- Added SHA256 generation with release step
> Added Sha256 release

- .github/workflows/deploy.yml
nit: Fix branch name for deploy script
> Fix branch name for deploy script

- docs/astro.config.mjs
> Fix domain name

- docs/astro.config.mjs
- docs/package-lock.json
- docs/package.json
- docs/public/robots.txt
- docs/src/content/docs/api/Entities/index.md
- Add sitemap and fix broken link
> Add sitemap and fix broken link

- README.md
- package.json
> Bump npm version and fix install script

- docs/src/content/docs/quickstart.md
- package-lock.json
Now documentation has npm installation step
> Update npm install script

- .github/workflows/release.yml
Support for linux, darwin, macos
1. ARM64 (AArch64)
> Support for AARCH64/ARM64 binaries

- package.json
- Fix issue for downloading and supported arm
> Fix issue for downloading and supported arm

- .github/workflows/release.yml
Looks like Github actions doesn't linux, windows arm64 cpu support
> Remove linux windows arm64

- .github/workflows/deploy.yml
- .gitignore
- docs/src/components/posthog.astro
- docs/src/content/docs/api/Conditions/index.mdx
- docs/src/content/docs/api/Entities/class.mdx
- docs/src/content/docs/api/Entities/index.mdx
- docs/src/content/docs/api/Entities/javadoc.mdx
- docs/src/content/docs/api/Entities/method.mdx
- docs/src/content/docs/api/Entities/method_call.mdx
- docs/src/content/docs/api/Entities/variable.mdx
- docs/src/content/docs/api/index.mdx
- docs/src/content/docs/cli-reference.mdx
- docs/src/content/docs/index.mdx
- docs/src/content/docs/overview.mdx
- docs/src/content/docs/queries/Android/android-webview-settings.mdx
- docs/src/content/docs/queries/DeadCode/unused-method-query.mdx
- docs/src/content/docs/queries/DeadCode/unused-variables-query.mdx
- docs/src/content/docs/queries/Javadoc/deprecated-access.mdx
- docs/src/content/docs/quickstart.mdx
- docs/src/layouts/PostHogLayout.astro
📈  added posthog analytics and injected token through build process
> Added posthog analytics to docs

- docs/src/content/docs/queries/Android/android-webview-settings.mdx
- Severity: Medium
- Category: Android
```sql
/**
* @name Android WebView JavaScript settings
* @description Enabling SetAllowUniversalAccessFromFileURLs leak sandbox access to file:/// URLs from any origin.
* @kind problem
* @id java/android/webview-javascript-enabled
* @problem.severity warning
* @security-severity 6.1
* @precision medium
* @tags security
* external/cwe/cwe-079
*/
FIND method_invocation WHERE name = 'setAllowUniversalAccessFromFileURLs' AND argumentname = 'true'
```
```sql
/**
* @name Android WebView JavaScript settings
* @description Enabling setAllowFileAccessFromFileURLs leak sandbox access to file:/// URLs.
* @kind problem
* @id java/android/webview-javascript-enabled
* @problem.severity warning
* @security-severity 6.1
* @precision medium
* @tags security
* …
```
> pathfinder queries: added few more webview api ruleset

- .github/workflows/build.yml
- Add code coverage to improve testcase
> Add code coverage app

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- Update issue and feature req templates
> Update issue and feature req templates

- .github/workflows/release.yml
- Fix windows powershell variables
> fix(build): Fix windows powershell variables

- package.json
- Bump npm package version to v0.0.23
> Bump npm package version

- sourcecode-parser/query.go
- test-src/android/app/src/main/java/com/ivb/udacity/adapter/movieGeneralAdapter.java
Fixes #90 
This PR moves the comment entities into core entities
> Move javadoc entity into primary core entity

- sourcecode-parser/construct_test.go
- sourcecode-parser/main.go
Add more testcase to increase coverage
> Add more testcase

- .github/workflows/deploy.yml
Migrate to cloudflare instead of github pages
> Added cloudflare deploy script

- .github/workflows/release.yml
- sourcecode-parser/go.mod
- sourcecode-parser/go.sum
- sourcecode-parser/go.work.sum
- sourcecode-parser/main.go
- sourcecode-parser/query.go
- sourcecode-parser/usage.go
- Report query events to posthog helps in analyzing the usage patterns
> Add posthog usage analytics log for cli tool

- sourcecode-parser/graph/construct_test.go
- added few testcase for coverage
> test(graph): added few testcase for coverage

- sourcecode-parser/graph/construct_test.go
- test(graph): Add few more testcase for coverage 📈
> test(graph): Add few more testcase for coverage 📈 

- sourcecode-parser/graph/construct_test.go
test(graph): Add few more testcase for coverage 📈
> test(graph): Add few more testcase for coverage 📈

- .github/workflows/release.yml
- fix failing release updated release upload action v4
> updated release upload action v4

- .github/workflows/npm-publish.yml
- added npm publish github action
> chore(ci): added npm publish github action

- README.md
- docs/src/content/docs/api/Entities/index.mdx
- docs/src/content/docs/api/Predicates/index.mdx
- docs/src/content/docs/api/index.mdx
- docs/src/content/docs/changelog.mdx
- docs/src/content/docs/index.mdx
- docs/src/content/docs/queries/Android/android-webview-settings.mdx
- docs/src/content/docs/queries/Javadoc/deprecated-access.mdx
- Update docs to include SELECT keyword 🥇 
- Update docs to reflect `predicate` support in queries
> chore(docs): update documentation to include SELECT keyword

- .github/workflows/docker-publish.yml
Fixed docker tag missing issue when building multiple tag
> fixed docker :whale: tag mistake

- .github/PULL_REQUEST_TEMPLATE.md
This pull request includes an update to the pull request template to improve the process of submitting and reviewing pull requests.
Enhancements to pull request template:
* [`.github/PULL_REQUEST_TEMPLATE.md`](diffhunk://#diff-18813c86948efc57e661623d7ba48ff94325c9b5421ec9177f724922dd553a35R1-R11): Added a section to encourage creating an issue for feedback before feature additions, referenced issues in PRs, and included a checklist for passing tests and linting.
> chore: added pr template

- docs/src/content/docs/index.mdx
- docs/src/content/docs/overview.mdx
> chore: fix title tag issue

- docs/package-lock.json
Ran `npm i` and regenerated `package-lock.json` for docs.
> chore: updated package-lock.json

- .github/workflows/deploy.yml
- docs/package-lock.json
- docs/package.json
Fix build script and add optional rollup dep
> chore: added rollup optional dep

- docs/astro.config.mjs
- docs/src/components/Header.astro
- docs/src/components/SiteTitle.astro
- docs/src/components/ThemeSelect.astro
- docs/src/content/docs/quickstart.mdx
- Add header component with relevant links
> docs: add header and links

- docs/src/components/CodeViewer.astro
- docs/src/content/docs/atlas/android/index.mdx
Same #218  but for android ruleset
> feat/atlas: add payground integration for android ruleset

- playground/pkg/middleware/cors.go
Add cpf main website to cors allowlist
> fix/playground: add cpf main website to cors allowlist

- docs/src/content/docs/blog/silence-the-noise-a-practical-guide-to-systematically-reducing-sast-false-positives.mdx
- **improved blog post content based on feedback**
- **added summary tldr**
> fix/blog: address and optimize feedbacks for sast false positive blogpost

- extension/secureflow/README.md
- extension/secureflow/package-lock.json
- extension/secureflow/package.json
- extension/secureflow/src/analysis/security-analyzer-ai.ts
- extension/secureflow/src/commands/scan-commands.ts
- extension/secureflow/src/extension.ts
- extension/secureflow/src/git/git-changes.ts
- extension/secureflow/src/models/scan-result.ts
- extension/secureflow/src/profiler/project-profiler.ts
- extension/secureflow/src/prompts/common/review-changes.txt
- extension/secureflow/src/prompts/prompt-loader.ts
- extension/secureflow/src/services/scan-storage-service.ts
- extension/secureflow/src/ui/secureflow-explorer.ts
- extension/secureflow/src/ui/webview/index.html
- extension/secureflow/src/ui/webview/main.js
- extension/secureflow/src/ui/webview/styles.css
- extension/secureflow/tsconfig.json
- extension/secureflow/webpack.config.js
https://marketplace.visualstudio.com/items?itemName=codepathfinder.secureflow
SecureFlow is now published to VSCode Marketplace with some tweaks
- **optimized security review on change command**
- **added right context profile for review command**
- **persisted the scan results**
- **improved the ui for webview details view**
- **updated timestamp view**
- **hide health status for now**
- **updated ui state for empty profile**
- **fixed ui state bug for dropdown profile selection**
- **updated readme.md**
- **updated readme, improved compat**
- **added prompts for code change review**
- **fixed code review context**
> SecureFlow v0.0.1

- extension/secureflow/package.json
> SecureFlow Release v0.0.2

- extension/secureflow/CHANGELOG.md
- extension/secureflow/package-lock.json
- extension/secureflow/package.json
- extension/secureflow/src/clients/gemini-client.ts
- extension/secureflow/src/services/analytics.ts
Fixed Gemini Client support for SecureFlow, 
- Support gemini pro 2.5, gemini 2.5 flash
- collected ai model usage via analytics
> Gemini Client Support for SecureFlow

- extension/secureflow/src/clients/openai-client.ts
Fix few config to make openai client to work
> secureflow/client: Fix few config for openai client

- extension/secureflow/CHANGELOG.md
- extension/secureflow/package.json
- extension/secureflow/src/clients/gemini-client.ts
- extension/secureflow/src/git/git-changes.ts
- extension/secureflow/src/prompts/common/review-changes.txt
- extension/secureflow/src/ui/secureflow-explorer.ts
- extension/secureflow/src/ui/webview/index.html
- extension/secureflow/src/ui/webview/main.js
- extension/secureflow/src/ui/webview/styles.css
- extension/secureflow/src/utils/format-timestamp.ts
- **added onboarding**
- **fixed scan history deletion**
- **added UI fixes for results page**
- **fixed some ui glitches**
- **bumped version**
- **added changelog**
> secureflow/release: v0.0.4 release

- .github/workflows/build.yml
- .github/workflows/publish-vscode-extension.yml
exclude go tests for vscode extension pull requests
> Exclude Go tests for VSCode extension

- extension/secureflow/src/ui/webview/index.html
- extension/secureflow/src/ui/webview/styles.css
Simplify onboarding - center button and remove irrelevant text
> refactor: simplify onboarding UI by removing descriptive text and centering get started button

- extension/secureflow/.prettierrc
- extension/secureflow/package-lock.json
- extension/secureflow/package.json
- extension/secureflow/src/analysis/security-analyzer-ai.ts
- extension/secureflow/src/analysis/security-analyzer.ts
- extension/secureflow/src/extension.ts
- extension/secureflow/src/prompts/common/review-changes.txt
- **refactor: improve selection analysis UI with webview and remove debug logs**
- **feat: integrate workspace profile context into security analysis**
- from now `ctrl+l` on any OS, with selected code should trigger secure code review with appropriate context magically
- improved UI for reporting results
> secureflow/fix: Improve shortcut selected secure code review and ux

- extension/secureflow/src/analysis/security-analyzer-ai.ts
- extension/secureflow/src/analysis/security-analyzer.ts
- extension/secureflow/src/clients/ai-client-factory.ts
- extension/secureflow/src/clients/ai-client.ts
- extension/secureflow/src/clients/claude-client.ts
- extension/secureflow/src/clients/gemini-client.ts
- extension/secureflow/src/clients/http-client.ts
- extension/secureflow/src/clients/openai-client.ts
- extension/secureflow/src/commands/scan-commands.ts
- extension/secureflow/src/extension.ts
- extension/secureflow/src/git/git-changes.ts
- extension/secureflow/src/models/profile-store.ts
- extension/secureflow/src/models/scan-result.ts
- extension/secureflow/src/models/security-issue.ts
- extension/secureflow/src/profiler/project-profiler.ts
- extension/secureflow/src/profiler/workspace-profiler-command.ts
- extension/secureflow/src/profiler/workspace-profiler.ts
- extension/secureflow/src/prompts/index.ts
- extension/secureflow/src/prompts/prompt-loader.ts
- extension/secureflow/src/services/analytics.ts
- extension/secureflow/src/services/profile-storage-service.ts
- extension/secureflow/src/services/scan-storage-service.ts
- extension/secureflow/src/services/sentry-service.ts
- extension/secureflow/src/settings/settings-manager.ts
- extension/secureflow/src/test/extension.test.ts
- extension/secureflow/src/ui/secureflow-explorer.ts
- extension/secureflow/src/utils/format-timestamp.ts
format code with prettier and fix indentation
> secureflow/chore: format code with prettier and fix indentation

- extension/secureflow/src/analysis/security-analyzer-ai.ts
- extension/secureflow/src/analysis/security-analyzer.ts
- extension/secureflow/src/git/git-changes.ts
- extension/secureflow/src/prompts/common/review-changes.txt
Moved from JSON parsing to XML based parsing to reduce error rates in claude model
> secureflow/parser: Moved to XML based parsing logic for reducing error rates

- extension/secureflow/src/extension.ts
- extension/secureflow/src/services/sentry-service.ts
Summary
- Introduces best-effort filtering to reduce Sentry exception noise originating from the shared Node.js process.
- Aims to lower false positives and focus error reporting on actionable issues.
Changes
- Updated `extension/secureflow/src/services/sentry-service.ts` to add noise filtering logic for known benign/expected exceptions.
- Wired the filtering into extension lifecycle in `extension/secureflow/src/extension.ts` so events pass through the filter before capture.
Rationale
- High noise in Sentry from shared process skews signal-to-noise ratio and obscures real issues.
- Filtering expected/benign patterns improves triage efficiency and alert quality.
Testing
- Manual verification with simulated exceptions to ensure:
- Filtered patterns are dropped and not reported.
- Legitimate …
> secureflow/enhancement: Best-effort Sentry noise filtering for shared Node.js process

- extension/secureflow/src/analysis/security-analyzer-ai.ts
- extension/secureflow/src/analysis/security-analyzer.ts
- extension/secureflow/src/git/git-changes.ts
Fixes markdown rendering issues in the SecureFlow webviews and improves file labeling in AI prompts/results for clearer context.
- security-analyzer: Add safe, minimal markdown renderer:
- Support fenced code blocks (```lang) and inline code (`code`)
- HTML escaping to prevent XSS
- Consistent styling for code blocks and inline code
- security-analyzer-ai: Use filename instead of full path in analysis prompt; remove debug logging
- git-changes: Align markdown rendering across views; consistent code styling and metadata display
- Markdown in AI output and descriptions previously rendered inconsistently or unsafe
- Full file paths in prompts led to noisy and brittle context; filenames are sufficient and cleaner
- Verified AI analysis webviews render:
- Inline code and fenced code blocks
- …
```
> secureflow/bugfix: Improve markdown rendering and file labeling in analysis results

- extension/secureflow/CHANGELOG.md
- extension/secureflow/package-lock.json
- extension/secureflow/package.json
- Use filename (not full path) in security analysis prompt for cleaner, less noisy context
- Remove debug logging during analysis to reduce noise
- Fix markdown rendering in webview output
See: extension/secureflow/CHANGELOG.md
shiva+windsurf/release-version-0.0.10 -> main
> secureflow/release: 0.0.10

- extension/secureflow/packages/secureflow-cli/lib/ai-client-factory.d.ts
- extension/secureflow/packages/secureflow-cli/lib/ai-client-factory.js
- extension/secureflow/packages/secureflow-cli/lib/ai-client.d.ts
- extension/secureflow/packages/secureflow-cli/lib/ai-client.js
- extension/secureflow/packages/secureflow-cli/lib/claude-client.d.ts
- extension/secureflow/packages/secureflow-cli/lib/claude-client.js
- extension/secureflow/packages/secureflow-cli/lib/gemini-client.d.ts
- extension/secureflow/packages/secureflow-cli/lib/gemini-client.js
- extension/secureflow/packages/secureflow-cli/lib/http-client.d.ts
- extension/secureflow/packages/secureflow-cli/lib/http-client.js
- extension/secureflow/packages/secureflow-cli/lib/index.d.ts
- extension/secureflow/packages/secureflow-cli/lib/index.js
- extension/secureflow/packages/secureflow-cli/lib/openai-client.d.ts
- extension/secureflow/packages/secureflow-cli/lib/openai-client.js
- extension/secureflow/packages/secureflow-cli/lib/types.d.ts
- extension/secureflow/packages/secureflow-cli/lib/types.js
- extension/secureflow/packages/secureflow-cli/package.json
- extension/secureflow/src/analysis/security-analyzer-ai.ts
- extension/secureflow/src/clients/index.ts
- extension/secureflow/src/profiler/project-profiler.ts
- extension/secureflow/tsconfig.json
Migrated AI client files from  to  to enable code reuse between VS Code extension and future CLI implementations.
**Changes:**
- Removed VS Code dependencies from AI clients
- Created JavaScript versions with TypeScript declarations
- Updated imports to use  package
- Configured TypeScript path mapping for proper module resolution
- All AI providers (Claude, OpenAI, Gemini) now VS Code-independent
**Files changed:** 21 files (+327, -185 lines)
> secureflow/enhancement: Extract AI client functionality into separate CLI package

- extension/secureflow/packages/secureflow-cli/bin/secureflow
- extension/secureflow/packages/secureflow-cli/lib/prompts/common/review-changes.txt
- extension/secureflow/packages/secureflow-cli/lib/prompts/scanner/file-request-instructions.txt
- extension/secureflow/packages/secureflow-cli/lib/prompts/scanner/final-analysis.txt
- extension/secureflow/packages/secureflow-cli/lib/prompts/scanner/final-iteration.txt
- extension/secureflow/packages/secureflow-cli/lib/prompts/scanner/initial-analysis.txt
- extension/secureflow/packages/secureflow-cli/lib/prompts/scanner/iterative-analysis.txt
- extension/secureflow/packages/secureflow-cli/scanner/ai-security-analyzer.js
- extension/secureflow/packages/secureflow-cli/scanner/cli-full-scan-command.js
- extension/secureflow/packages/secureflow-cli/scanner/file-request-handler.js
- extension/secureflow/packages/secureflow-cli/scanner/index.js
- extension/secureflow/packages/secureflow-cli/scanner/project-analyzer.js
This PR introduces a comprehensive AI-driven security scanner for the SecureFlow CLI that performs intelligent, iterative analysis of codebases using LLM file requests.
- **LLM File Request System**: XML-based file requests with iterative analysis
- **Smart Project Detection**: Auto-detects Go, Node.js, Python projects  
- **Beautiful Directory Tree**: Unicode tree display with file line counts
- **Security Filtering**: Project scope validation, symlink protection, hidden file filtering
- **Real AI Integration**: Connected to existing AIClientFactory (Claude, OpenAI, Gemini)
```bash
secureflow scan [project-path] --model claude-3-5-sonnet-20241022 --format json --output results.json
```
Successfully tested on real Go project:
- ✅ 4 security issues found (1 High, 3 Medium severity)
- ✅ …
> secureflow/enhancement: Implement AI-powered full security scanner with iterative file analysis

- extension/secureflow/CHANGELOG.md
- extension/secureflow/package-lock.json
- extension/secureflow/package.json
This release introduces significant new capabilities to SecureFlow, particularly the standalone CLI package and enhanced security analysis features.
**Version Bump:**
- Updated from version 0.0.10 to 0.0.11
- Updated package.json and package-lock.json accordingly
**CHANGELOG Updates:**
- Added comprehensive release notes documenting all features since 0.0.10
- Detailed breakdown of new features, improvements, and technical changes
- **SecureFlow CLI Package**: Introduced standalone CLI tool for security analysis outside VS Code
- **AI-Powered Security Scanner**: New iterative file analysis system with intelligent file request handling  
- **Full Workspace Scanning**: Comprehensive security scanning with up to 10 iterations for thorough analysis
- **CLI Project Profiling**: AI-powered …
> secureflow/release: Version 0.0.11 with CLI package and enhanced security features

- extension/secureflow/packages/secureflow-cli/config/model-context-limits.json
- extension/secureflow/packages/secureflow-cli/lib/claude-client.js
- extension/secureflow/packages/secureflow-cli/lib/gemini-client.js
- extension/secureflow/packages/secureflow-cli/lib/openai-client.js
- extension/secureflow/packages/secureflow-cli/lib/token-display.js
- extension/secureflow/packages/secureflow-cli/lib/token-tracker.js
- extension/secureflow/packages/secureflow-cli/lib/workspace-analyzer/workspace-analyzer.js
- extension/secureflow/packages/secureflow-cli/package.json
- extension/secureflow/packages/secureflow-cli/profiler/cli-profile-command.js
- extension/secureflow/packages/secureflow-cli/profiler/cli-project-profiler.js
- extension/secureflow/packages/secureflow-cli/scanner/ai-security-analyzer.js
- extension/secureflow/packages/secureflow-cli/scanner/cli-full-scan-command.js
This PR introduces comprehensive token tracking and model context limits management for all LLM API calls in the SecureFlow CLI, providing better cost monitoring and usage transparency.
- **New TokenTracker class** (`lib/token-tracker.js`) with 275+ lines of comprehensive token management
- Real-time token usage monitoring for all AI API calls
- Session-based tracking with pre-call and post-call usage display
- Detailed cost estimation based on model-specific pricing
- Color-coded console output for better visibility
- **Comprehensive model database** (`config/model-context-limits.json`) with 124 entries
- Support for 13+ AI models including Claude, GPT, and Gemini variants
- Context window limits, pricing information, and model capabilities
- Structured data for intelligent model …
> secureflow/enhancement: Add token tracking and model context limits for LLM API calls

- extension/secureflow/packages/secureflow-cli/config/model-context-limits.json
- extension/secureflow/packages/secureflow-cli/lib/ai-client-factory.js
- extension/secureflow/packages/secureflow-cli/lib/ai-client.d.ts
- extension/secureflow/packages/secureflow-cli/lib/ai-client.js
- extension/secureflow/packages/secureflow-cli/lib/claude-client.d.ts
- extension/secureflow/packages/secureflow-cli/lib/claude-client.js
- extension/secureflow/packages/secureflow-cli/lib/config.js
- extension/secureflow/packages/secureflow-cli/lib/gemini-client.js
- extension/secureflow/packages/secureflow-cli/lib/index.d.ts
- extension/secureflow/packages/secureflow-cli/lib/index.js
- extension/secureflow/packages/secureflow-cli/lib/ollama-client.js
- extension/secureflow/packages/secureflow-cli/lib/openai-client.js
- extension/secureflow/packages/secureflow-cli/lib/prompts/common/security-review-cli.txt
- extension/secureflow/packages/secureflow-cli/lib/prompts/scanner/file-request-instructions.txt
- extension/secureflow/packages/secureflow-cli/lib/prompts/scanner/final-iteration.txt
- extension/secureflow/packages/secureflow-cli/lib/prompts/scanner/iterative-analysis.txt
- extension/secureflow/packages/secureflow-cli/lib/token-tracker.js
- extension/secureflow/packages/secureflow-cli/lib/types.d.ts
- extension/secureflow/packages/secureflow-cli/lib/types.js
- extension/secureflow/packages/secureflow-cli/scanner/ai-security-analyzer.js
- extension/secureflow/packages/secureflow-cli/scanner/cli-full-scan-command.js
- extension/secureflow/packages/secureflow-cli/scanner/project-analyzer.js
This pull request adds support for the Ollama provider and its Qwen 3:4B model to the SecureFlow CLI, and introduces improvements to the AI client architecture for better multi-provider support and extensibility. It also adds a comprehensive security review prompt for code analysis. The most important changes are grouped below.
**Ollama Provider and Model Support:**
* Added Ollama provider and Qwen 3:4B model (256K context window, 32K output tokens) to `model-context-limits.json`.
* Implemented new `OllamaClient` class for interacting with the Ollama API, including support for both standard and streaming requests, and handling of message formatting and result parsing.
* Registered `OllamaClient` in the client factory and export modules, and updated provider inference logic to support …
> secureflow/feature: Add Ollama client support with qwen3:4b model integration

- extension/secureflow/.gitignore
- extension/secureflow/.vscode/settings.json
- extension/secureflow/packages/secureflow-cli/Dockerfile
- extension/secureflow/packages/secureflow-cli/docker-compose.yml
- extension/secureflow/packages/secureflow-cli/lib/gemini-client.js
This pull request introduces several improvements to the SecureFlow CLI, focusing on better support for Docker-based plugin analysis and enhanced reliability when interacting with the Gemini API. The main changes include adding a Dockerfile and docker-compose setup for the CLI, improving `.gitignore` and VSCode settings, and implementing robust rate limit handling with retries in the Gemini API client.
**Dockerization and Environment Setup:**
* Added a production-ready `Dockerfile` for the SecureFlow CLI, including best practices such as using a non-root user, installing only required dependencies, setting up health checks, and defining volume mount points for results and configuration.
* Introduced a `docker-compose.yml` file to orchestrate the SecureFlow CLI container, supporting …
> feat: add Docker containerization and retry logic for Gemini API client

- extension/secureflow/packages/secureflow-cli/scanner/ai-security-analyzer.js
- extension/secureflow/packages/secureflow-cli/scanner/cli-full-scan-command.js
- extension/secureflow/packages/secureflow-cli/scanner/file-request-handler.js
This pull request primarily refines the CLI output and logging for the SecureFlow scanner, focusing on making messages clearer and less verbose, especially during file handling and DefectDojo integration. The changes improve readability and streamline user feedback, while also removing or commenting out less essential logs.
**CLI Output Improvements**
* Changed summary output in `CLIFullScanCommand` to use full severity names (e.g., `Critical`, `High`, `Medium`, `Low`, `Info`) instead of abbreviations for better clarity.
* Updated file request logs in `FileRequestHandler` to a more structured format, showing both the file path and the reason for reading, making it easier to follow file access during scans.
**DefectDojo Integration Logging**
* Removed loader and validation messages, and …
> refactor: streamline CLI output and simplify DefectDojo submission flow
