.github/workflows/release.yml
.gitignore
package-lock.json
package.json

- Used `go-npm`  package to publish go binaries
- Updated release process to include `tar.gz` and `zip`

Added npm publish config and fix release

---

sourcecode-parser/construct.go

Previously method invocation call param wasn't handled properly. Now it parses that with string literal check too

Fixed method invocation param

---

docs/src/content/docs/queries/Android/android-webview-settings.mdx

```sql
/**
* @name Android WebView JavaScript settings
* @description Enabling JavaScript execution in a WebView can result in cross-site scripting attacks.
* @kind problem
* @id java/android/websettings-javascript-enabled
* @problem.severity warning
* @security-severity 6.1
* @precision medium
* @tags security
* external/cwe/cwe-079
*/
FIND method_invocation WHERE name = 'setJavaScriptEnabled' AND argumentname = 'true'
```

Added query to find android webview setting

---

sourcecode-parser/model/javadoc.go
sourcecode-parser/model/javadoc_test.go
sourcecode-parser/query.go

Method chaining is powerful feature to write models and expose methods to support runtime method filtering instead of compile time/construction time of AST
from now on 🚀 you'll be able to chain methods for javadoc object and methods. More support for entities and methods coming soon in future PR.
```sql
FIND method_declaration AS md WHERE md.getDoc().GetCommentAuthor() == "shivasurya"
```
- CI 🟢

Support Method Chaining for Attributes and Entities

---

docs/src/content/docs/queries/Android/android-webview-settings.mdx
pathfinder-rules/android/webview.cql
sourcecode-parser/main.go
sourcecode-parser/main_test.go
test-src/android/app/src/main/java/com/ivb/udacity/movieDetailActivity.java

From now on, you could execute queries from file named `*.cql` 🥇 
```bash
$ pathfinder --project <PATH_TO_SCAN> --query-file ../pathfinder-rules/android/webview.cql
Worker 1 ....... Done processing file Results.java
Worker 2 ....... Done processing file movieListActivity.java
Worker 1 ....... Done processing file NetworkAPI.java
Worker 2 ....... Done processing file ExampleUnitTest.java
Worker 3 ....... Done processing file movieDetailFragment.java
Worker 4 ....... Done processing file movieListActivity.java
Worker 5 ....... Done processing file Results.java
Progress: 100%
2024/08/23 09:29:13 Elapsed time:  42.888667ms
2024/08/23 09:29:13 Graph built successfully
Executing query: FIND method_invocation AS mi WHERE mi.getName() == "setJavaScriptEnabled" && "true" in mi.getArgumentName() …
```

feature(query): introduce to execute queries from `CQL` file 🚀 

---

.github/workflows/release.yml

The release script for macos, windows had missed -X param while building the binary.

fixed release script variable arg

---

sourcecode-parser/go.mod
sourcecode-parser/go.sum
sourcecode-parser/go.work.sum

Recent change in posthog broke Capture event. https://github.com/PostHog/posthog-go/issues/69
- CI 🟢

bug(posthog): upgrade posthog go version

---

sourcecode-parser/antlr/listener_impl.go
sourcecode-parser/antlr/listener_impl_test.go
sourcecode-parser/graph/query.go
sourcecode-parser/graph/query_test.go
test-src/android/app/src/test/java/com/ivb/udacity/ExampleUnitTest.java

closes #98 
This PR attempts to add support for querying multiple entities in a single query. This can be naively supported by generating cartesian product of the entity nodes and applying filters.
```sql
FIND method_declaration AS md, class_declaration AS cd 
WHERE md.getVisibility() == cd.getVisibility()
```

Support multiple entity selection via cartesian product 📐

---

sourcecode-parser/antlr/listener_impl.go
sourcecode-parser/antlr/listener_impl_test.go
sourcecode-parser/cmd/query.go

This PR adds better error reporting for query syntax issues instead of crashing the whole application. 🎸 
```bash
Progress: 100%
2024/09/07 22:25:31 Elapsed time:  456.686083ms
2024/09/07 22:25:31 Graph built successfully
Path-Finder Query Console: 
>wdfweldjfgw
Executing query: wdfweldjfgw
PathFinder Query syntax error: 
line 1:0 missing 'FIND' at 'wdfweldjfgw'
line 2:0 mismatched input '<EOF>' expecting 'AS'
```

added better error handling for query parsing :star:

---

pathfinder-rules/test/ClassInstanceExpr.cql
sourcecode-parser/cmd/query.go
sourcecode-parser/cmd/query_test.go
sourcecode-parser/graph/construct.go
sourcecode-parser/graph/construct_test.go
sourcecode-parser/graph/query.go
sourcecode-parser/graph/util.go
sourcecode-parser/graph/util_test.go
sourcecode-parser/model/expr.go
sourcecode-parser/model/expr_test.go

This PR adds support for indexing and querying `ClassInstanceExpr` 
Example:
Source:
```java
Socket so = new Socket("www.google.com", 80)
```
Query:
```sql
FROM ClassInstanceExpr AS cie
WHERE cie.getClassName() == "Socket"
SELECT cie, "Insecure Socket connection found"
```

feat: Support for `ClassInstanceExpr`

---

pathfinder-rules/java/UnEncryptedSocketConnection.cql
test-src/android/app/src/main/java/com/ivb/udacity/movieDetailActivity.java

This pathfinder rule helps detecting unencrypted socket, serversocket connections in source code.
example:
```java
Socket socket = new Socket("host", 8080)
ServerSocket ss = new ServerSocket("host", 8000)
```

pathfinder rules: added unencrypted socket connection detection rule

---

sourcecode-parser/graph/construct.go
sourcecode-parser/graph/construct_test.go

Adding row and column number to make the entities unique across files and project path

fixed unique id issue for generating unique id

---

docs/astro.config.mjs
docs/src/content/docs/blog/codeql-oss-alternative.mdx
docs/src/content/docs/blog/index.mdx

added blog listing under /blog

chore: added blog listing

---

.github/workflows/docker-publish.yml
Dockerfile
README.md
action.yml
entrypoint.sh
sourcecode-parser/cmd/ci.go
sourcecode-parser/cmd/ci_test.go
sourcecode-parser/graph/util.go

- Introduced a new GitHub Action template to streamline CI/CD workflows.
- Created an `action.yml` file to define the action metadata and inputs.
- This addition will help automate processes and improve project maintainability.
🔧 This enhancement sets the foundation for future automation tasks.

✨ Add GitHub Action template with action.yml

---

docs/src/content/docs/blog/finding-webview-misconfigurations-android.mdx

- fix query name issue in blog post

fix query name issue in blog post :bug:

---

docs/src/content/docs/ci.mdx
docs/src/content/docs/index.mdx

This pull request includes updates to the documentation and minor code adjustments to improve clarity and functionality. The most important changes include updating the Docker action reference, modifying a quote in the code example, and enhancing the visual layout of the documentation.
Documentation updates:
* [`docs/src/content/docs/ci.mdx`](diffhunk://#diff-1d43fd842bcd3e3583da1c2d30c6e3d1ebef9375559ac6aa449c13e9ef0a9f57L29-R29): Updated the Code-Pathfinder SAST Scan GitHub Action to use the `main` branch instead of a specific fix branch.
* [`docs/src/content/docs/index.mdx`](diffhunk://#diff-ae669176eb85e8e00b8a6b2541c7d55deba8790db6fba3384459244bc8c8e4f7L36-R37): Modified the quote in the `main` method example to remove unnecessary escape characters.
Visual layout enhancements:
* …

chore: improve doc site

---

sourcecode-parser/graph/construct.go
sourcecode-parser/graph/construct_test.go
sourcecode-parser/graph/java/parse_statement.go
sourcecode-parser/graph/java/parse_statement_test.go
sourcecode-parser/graph/query.go
sourcecode-parser/model/stmt.go
test-src/android/app/src/main/java/com/ivb/udacity/movieDetailActivity.java

This pull request introduces support for parsing and handling Java `break` statements within the code graph. The changes include updates to the parser, model, and tests to incorporate this new feature.
* Added `BreakStmt` to the `Node` struct in `sourcecode-parser/graph/construct.go` to represent break statements in the graph.
* Implemented the `ParseBreakStatement` function in `sourcecode-parser/graph/java/parse_statement.go` to parse Java break statements.
* Introduced the `BreakStmt` struct in `sourcecode-parser/model/stmt.go` to model break statements.
* Updated the `buildGraphFromAST` function in `sourcecode-parser/graph/construct.go` to handle break statements and add them to the graph.
* Added support for querying `BreakStmt` in `sourcecode-parser/graph/query.go` by adding relevant …

feature: 🍺 Support for  `BreakStmt`

---

sourcecode-parser/graph/construct.go
sourcecode-parser/graph/construct_test.go
sourcecode-parser/graph/java/parse_statement.go
sourcecode-parser/graph/java/parse_statement_test.go
sourcecode-parser/graph/query.go
sourcecode-parser/model/stmt.go
sourcecode-parser/model/stmt_test.go
test-src/android/app/src/main/java/com/ivb/udacity/movieDetailActivity.java

This pull request introduces support for parsing and handling `continue` statements in the code graph. The changes include updates to the core parsing logic, graph construction, and associated test cases.
* Added `ContinueStmt` field to the `Node` struct in `sourcecode-parser/graph/construct.go` to handle `continue` statements.
* Implemented logic to parse `continue` statements in `sourcecode-parser/graph/construct.go` and add them to the code graph.
* Created a new function `ParseContinueStatement` in `sourcecode-parser/graph/java/parse_statement.go` to parse `continue` statements from the AST.
* Updated `TestBuildGraphFromAST` in `sourcecode-parser/graph/construct_test.go` to include `continue` statements in test cases. [[1]](diffhunk://#diff-0a3c4e201b37c63ddb996c242b9259233f31714f17ff8 …

feature: 🍺 Support for `Continue` statement

---

sourcecode-parser/graph/construct.go
sourcecode-parser/graph/construct_test.go
sourcecode-parser/graph/java/parse_statement.go
sourcecode-parser/graph/java/parse_statement_test.go
sourcecode-parser/graph/query.go
sourcecode-parser/model/stmt.go
sourcecode-parser/model/stmt_test.go
test-src/android/app/src/main/java/com/ivb/udacity/movieDetailActivity.java

This pull request introduces support for parsing and handling `yield` statements in Java source code within the `sourcecode-parser` package. The changes include modifications to the core parsing logic, the addition of new test cases, and updates to the model and query handling to accommodate `yield` statements.
* Added `YieldStmt` to the `Node` struct in `sourcecode-parser/graph/construct.go` and implemented parsing logic for `yield` statements. [[1]](diffhunk://#diff-1774f73dedf66ded4170ae5e8f0988a1782789c07e7224bb863224f037da8f84L55-R56) [[2]](diffhunk://#diff-1774f73dedf66ded4170ae5e8f0988a1782789c07e7224bb863224f037da8f84R184-R198)
* Introduced `ParseYieldStatement` function in `sourcecode-parser/graph/java/parse_statement.go` to handle the parsing of `yield` statements.
* Added …

feature: 🍺 Support for `YieldStmt` statement

---

sourcecode-parser/graph/construct.go
sourcecode-parser/graph/java/parse_statement.go
sourcecode-parser/graph/java/parse_statement_test.go
sourcecode-parser/graph/query.go
sourcecode-parser/model/stmt.go
sourcecode-parser/model/stmt_test.go
test-src/android/app/src/main/java/com/ivb/udacity/movieDetailActivity.java

This pull request introduces support for parsing and handling `assert` statements in the codebase. The changes include updates to various parts of the code to recognize, parse, and test `assert` statements, similar to how `yield` statements are handled.
* Added `AssertStmt` to the `Node` struct to support `assert` statements. (`sourcecode-parser/graph/construct.go`)
* Implemented parsing logic for `assert` statements in the `buildGraphFromAST` function. (`sourcecode-parser/graph/construct.go`)
* Created `ParseAssertStatement` function to parse `assert` statements. (`sourcecode-parser/graph/java/parse_statement.go`)
* Added unit tests for `ParseAssertStatement` to ensure correct parsing of various `assert` statement formats. (`sourcecode-parser/graph/java/parse_statement_test.go`)
* Added …

feature: 🍺 Support for `AssertStmt` Node statement

---

sourcecode-parser/graph/construct.go
sourcecode-parser/graph/construct_test.go
sourcecode-parser/graph/java/parse_statement.go
sourcecode-parser/graph/query.go
sourcecode-parser/model/stmt.go
sourcecode-parser/model/stmt_test.go

This pull request introduces support for parsing and handling return statements within the `sourcecode-parser` module. The main changes involve adding a new `ReturnStmt` type, updating the graph construction logic to recognize return statements, and extending the test cases to cover this new functionality.
* Added `ReturnStmt` to the `Node` struct in `construct.go` to support return statements in the graph.
* Implemented parsing logic for return statements in `ParseReturnStatement` function in `parse_statement.go`.
* Updated the `buildGraphFromAST` function to handle return statements by creating `ReturnStmt` nodes.
* Added `GetReturnStmt` method in `query.go` to retrieve return statements from the environment.
* Modified the `TestBuildGraphFromAST` function to include return statements …

feature: Support for `ReturnStmt` statement

---

README.md

docker run -v "./src:/src" shivasurya/code-pathfinder:stable-latest **pathfinder** ci --project /src/code-pathfinder/test-src --ruleset cpf/java
```
unknown command "pathfinder" for "pathfinder"
Error: unknown command "pathfinder" for "pathfinder"
Run 'pathfinder --help' for usage.
```
right answer:
`docker run -v "./src:/src" shivasurya/code-pathfinder:stable-latest ci --project /src/code-pathfinder/test-src --ruleset cpf/java`

fix docker command

---

sourcecode-parser/graph/construct.go
sourcecode-parser/graph/construct_test.go
sourcecode-parser/graph/java/parse_statement.go
sourcecode-parser/graph/java/parse_statement_test.go
sourcecode-parser/graph/query.go
sourcecode-parser/model/stmt.go
sourcecode-parser/model/stmt_test.go

This pull request introduces support for parsing and handling block statements in the code graph. The most important changes include adding a new `BlockStmt` type, updating the graph construction to recognize block statements, and enhancing the query environment to support this new type.
* [`sourcecode-parser/graph/construct.go`](diffhunk://#diff-1774f73dedf66ded4170ae5e8f0988a1782789c07e7224bb863224f037da8f84R58): Added `BlockStmt` to the `Node` struct and updated `buildGraphFromAST` to handle "block" node types by creating and adding `BlockStmt` nodes to the graph. [[1]](diffhunk://#diff-1774f73dedf66ded4170ae5e8f0988a1782789c07e7224bb863224f037da8f84R58) [[2]](diffhunk://#diff-1774f73dedf66ded4170ae5e8f0988a1782789c07e7224bb863224f037da8f84R187-R201)
* …

feature: 🍺  Support for `BlockStmt` statement

---

docs/src/content/docs/api/Entities/assertstmt.mdx
docs/src/content/docs/api/Entities/blockstmt.mdx
docs/src/content/docs/api/Entities/index.mdx
docs/src/content/docs/api/Entities/returnstmt.mdx
sourcecode-parser/.golangci.yml
sourcecode-parser/cmd/query.go
sourcecode-parser/graph/query.go

Update documentation to include latest feature such as `BlockStmt`, `IfStmt` and loops. (more to add here)

doc: refresh documentation for latest statement support

---

docs/src/content/docs/api/Entities/assertstmt.mdx
docs/src/content/docs/api/Entities/blockstmt.mdx
docs/src/content/docs/api/Entities/returnstmt.mdx

Chore: Update SEO misaligned title tag

chore: update seo title

---

docs/src/content/docs/atlas/index.mdx
docs/src/content/docs/atlas/java/index.mdx
pathfinder-rules/java/XMLExternalEntity.cql
sourcecode-parser/cmd/ci_test.go
test-src/android/app/src/main/java/com/ivb/udacity/movieDetailFragment.java

This pull request includes updates to the Java documentation and introduces a new rule for detecting XML External Entity (XXE) vulnerabilities. Additionally, it modifies some Java code examples to highlight secure configurations.
* [`pathfinder-rules/java/XMLExternalEntity.cql`](diffhunk://#diff-ba6a47aa1826e349f7e8d7dfcf5e2b30e3bd6d02c4620518e83ab9e0e4b4e3b6R1-R22): Added a new rule to detect insecure XML parser configurations that could lead to XXE attacks.
* [`test-src/android/app/src/main/java/com/ivb/udacity/movieDetailFragment.java`](diffhunk://#diff-77fa05a55906fc45875c4f4411e2a4f5b0ac9ecfeaccc9e4f078ea3ecbe28a44R176-R179): Added insecure XML parser configurations in two methods to demonstrate potential vulnerabilities. [[1]](diffhunk://#diff-77fa05a55906fc45875c4f4411e2a4f5b0ac9ecf …

atlas/rule: add basic xxe rule for java xml parser

---

docs/package-lock.json
docs/package.json
docs/src/components/Code.astro
docs/src/components/CodeViewer.astro
docs/src/components/CollapsibleCode.astro
docs/src/content/docs/atlas/java/index.mdx
docs/src/styles/layout.css
playground/main.go
playground/pkg/handlers/query.go
playground/pkg/middleware/cors.go

From now on `atlas` rules page will be able to natively run code-pathfinder (codeql) queries directly on the code and return output. 🛳️
Edit Code -> Apply rule -> Run from the browser 🚀 
This pull request introduces significant updates to the `docs` package, focusing on enhancing code visualization and syntax highlighting capabilities. The most important changes include the addition of new dependencies for CodeMirror and related packages, the creation of new components for code display, and the integration of CodeMirror for syntax highlighting.

feat/atlas: add playground integration for atlas ruleset

---

extension/secureflow/.windsurf/workflows/pr.md

Summary
- Add `/pr` workflow at [extension/secureflow/.windsurf/workflows/pr.md](cci:7://file:///Users/shiva/src/shivasurya/code-pathfinder/extension/secureflow/.windsurf/workflows/pr.md:0:0-0:0) to standardize PR creation from the CLI.
Details
- Documents steps to review commits vs main, craft title/body, select labels, assign, and create the PR using `gh`.
- Reinforces naming convention: `secureflow/{feature/release/chore/bugfix/enhancement}: ...`.
Why
- Improves contributor velocity and PR quality with a clear, repeatable checklist.

secureflow/chore: Add PR creation workflow for consistent CLI-based PRs

---

extension/secureflow/packages/secureflow-cli/bin/secureflow
extension/secureflow/packages/secureflow-cli/lib/defectdojo-client.js
extension/secureflow/packages/secureflow-cli/scanner/cli-full-scan-command.js

This pull request adds automated integration with DefectDojo to the `CLIFullScanCommand` for improved vulnerability management. Now, findings from a full scan can be automatically submitted to DefectDojo if the relevant API configuration is provided, and users receive a summary of the submission with next steps.
* Added support for DefectDojo API submission by importing `DefectDojoClient` and accepting `defectDojoOptions` in the command constructor. [[1]](diffhunk://#diff-e6670fbe7460940e20c82d71a6715466a4ffb32f54b4f34da6896749ad33fa92R12) [[2]](diffhunk://#diff-e6670fbe7460940e20c82d71a6715466a4ffb32f54b4f34da6896749ad33fa92R22)
* Implemented the `_submitToDefectDojo` method to validate configuration, create engagements/tests if needed, and submit findings to DefectDojo, with detailed …

feat: add DefectDojo integration for direct scan result submission

---

extension/secureflow/packages/secureflow-cli/lib/token-display.js
extension/secureflow/packages/secureflow-cli/scanner/ai-security-analyzer.js
extension/secureflow/packages/secureflow-cli/scanner/cli-full-scan-command.js

This pull request focuses on making the CLI output more concise and user-friendly by streamlining the display of token usage summaries and removing verbose or redundant summary sections, particularly around DefectDojo integration. The changes also include minor cleanup of console output for clarity.
**CLI Output Improvements:**
* Refactored the `TokenDisplay.displayFinalSummary` method to show a compact, single-line summary of token usage, including input/output tokens, iterations, and usage percentages; added input validation and safer handling of missing data. The detailed per-iteration breakdown and verbose formatting are now commented out to keep output concise.
**DefectDojo Integration Cleanup:**
* Removed the `_displayDefectDojoSubmissionSummary` method and its invocation, …

feat/secureflow: compact ui styles

---

extension/secureflow/packages/secureflow-cli/scanner/cli-full-scan-command.js

This pull request makes a small but important change to how finding severities are counted in the CLI scan summary. The code now ensures that severity comparisons are case-insensitive, which helps prevent missed findings due to inconsistent casing.
* Severity counts in the scan summary now use `toLowerCase()` when comparing finding severities, making the logic robust against case differences in input data. (`extension/secureflow/packages/secureflow-cli/scanner/cli-full-scan-command.js`)

fix: add case-insensitive severity filtering for defect findings summary

---

extension/secureflow/packages/secureflow-cli/config/model-context-limits.json
extension/secureflow/packages/secureflow-cli/lib/ai-client-factory.js
extension/secureflow/packages/secureflow-cli/lib/grok-client.d.ts
extension/secureflow/packages/secureflow-cli/lib/grok-client.js
extension/secureflow/packages/secureflow-cli/lib/token-tracker.js
extension/secureflow/packages/secureflow-cli/lib/types.d.ts
extension/secureflow/packages/secureflow-cli/lib/types.js

This pull request adds support for xAI's Grok-4-fast-reasoning model to the SecureFlow CLI, including configuration, client implementation, and usage tracking. The changes ensure Grok can be selected, invoked, and its token usage properly tracked, alongside updates to recommendations and documentation.
**Grok model integration:**
* Added Grok-4-fast-reasoning model configuration to `model-context-limits.json`, specifying its context window, output limits, and metadata notes. [[1]](diffhunk://#diff-64ffe8314ee119235a30bf3feb39d9553c838a71bb40e94abfaa4722d54b4968R85-R95) [[2]](diffhunk://#diff-64ffe8314ee119235a30bf3feb39d9553c838a71bb40e94abfaa4722d54b4968L101-R114)
* Updated recommendations and reasoning lists to include Grok-4-fast-reasoning as a preferred large-context and reasoning …

feat: add Grok-4 AI model support with 2M context window and OpenAI-compatible API client

---

extension/secureflow/packages/secureflow-cli/lib/animated-loader.js
extension/secureflow/packages/secureflow-cli/lib/token-display.js
extension/secureflow/packages/secureflow-cli/scanner/ai-security-analyzer.js
extension/secureflow/packages/secureflow-cli/tools/mgmt/analyze-plugins.sh

This pull request introduces several improvements and refinements to the SecureFlow CLI, focusing on usability, clarity of output, and robustness in plugin extraction. The most significant changes include enhanced handling of plugin directory structures during extraction, improved output formatting for token statistics, and minor adjustments to logging for a cleaner user experience.
* Refactored the plugin extraction process in `analyze-plugins.sh` to handle typical WordPress plugin directory structures, ensuring plugin contents are moved correctly and hidden files are preserved. Added cleanup of temporary extraction directories for robustness.
* Updated error handling to ensure temporary extraction directories are cleaned up properly on extraction failure.
* Improved the formatting of …

secureflow-cli: ux improvements in logs

---

extension/secureflow/packages/secureflow-cli/README.md
extension/secureflow/packages/secureflow-cli/package-lock.json
extension/secureflow/packages/secureflow-cli/package.json

This pull request updates the `secureflow-cli` package with a new version, adjusts licensing, and makes minor documentation changes. The most important changes are grouped below:
**Release and Licensing Updates:**
* Bumped the package version from `0.0.1` to `0.0.2` in both `package.json` and `package-lock.json` to indicate a new release. [[1]](diffhunk://#diff-38c4dc2fbd0ecfe756343be72b2729126fc0e80cf676fb48d85c8378117a8447L3-R3) [[2]](diffhunk://#diff-54cfd254beaa6b9f156d91d40ce9727a48c9f5dd209c3fb3de06f95cefe5efa2L3-R19)
* Changed the package license from `MIT` to `AGPL-3.0` in `package-lock.json` to match `package.json` and reflect a stronger copyleft license.
**Platform Requirements:**
* Added an `engines` field to `package-lock.json` specifying Node.js version `>=16.0.0` as a …

secureflow-cli: release v0.0.2

---

extension/secureflow/CHANGELOG.md
extension/secureflow/package-lock.json
extension/secureflow/package.json
extension/secureflow/packages/secureflow-cli/package-lock.json
extension/secureflow/packages/secureflow-cli/package.json

This pull request updates SecureFlow to version 0.0.12, introducing new features and improvements focused on security analysis capabilities and AI model support. The most notable changes include the addition of a standalone CLI tool, support for a new AI model, and the removal of a deprecated model. There are also enhancements to security guidelines and dependency updates.
**New Features:**
* Added a standalone SecureFlow CLI tool for security analysis outside of VS Code, with updated dependencies and licensing (`@codepathfinder/secureflow-cli` package version bumped to 0.0.3, license changed to AGPL-3.0, and minimum Node.js version set to 16.0.0). [[1]](diffhunk://#diff-62c599eb684d3fa3d5418f9543e4219f6edf145d5667aef673fb1858e2687508L5384-R5394) …

chore: bump version to 0.0.12 and add Grok AI model support
